### ISSUE TITLE
AWS Lambda issue, "window is not defined"

### ISSUE THREAD

**Issue by oliver1706** [zpxp/manual-promise#7]
Hi. When I try to use this package in AWS lambda, I get a reference error, "window is not defined". We are using webpack as well. I've looked at the code and it seems like it should handle this case, but unfortunately I haven't been able to fix this issue. Would really appreciate any help on this! Thank you.

**Comment by zpxp** [comment]
Hi oliver, are you running this in a nodejs environment? I can change `window` to `self` and that might solve your issue.

**Comment by oliver1706** [comment]
Yeah that's correct. That'd be excellent thanks, hopefully that would work.

**Comment by zpxp** [comment]
All pushed. Check out version ` 2.0.2 ` and see if that works

**Comment by oliver1706** [comment]
Cheers!
Build host is down, so I manually replicated the commit in experimental and it seems alright, no undefined error at least. Thanks, I'll let you know tomorrow if it's 100%, if that's okay?
Thank you!

**Comment by zpxp** [comment]
Im guessing this is solved so closing
